version: '3'
networks:
  webwolflocal:
services:
  webgoat:
    hostname: www.webgoat.local
    image: webgoat/webgoat-8.0
    environment:
      - WEBGOAT_PORT=8080
      - WEBGOAT_SSLENABLED=false
      - WEBWOLF_HOST=webwolf
      - WEBWOLF_PORT=9090
      - TZ=Europe/Amsterdam
    volumes:
      - .:/home/webgoat/.webgoat
    working_dir: /home/webgoat
    command: --server.address=0.0.0.0
    networks:
      webwolflocal:
        aliases:
          - goat.webgoat.local
  webwolf:
    image: webgoat/webwolf
    environment:
      - WEBWOLF_HOST=webwolf
      - WEBWOLF_PORT=9090
      - TZ=Europe/Amsterdam
    command: --spring.datasource.url=jdbc:hsqldb:hsql://webgoat:9001/webgoat --server.address=0.0.0.0
    networks:
      webwolflocal:
        aliases:
          - wolf.webwolf.local
    depends_on:
            - webgoat
  reverseproxy:
    hostname: www.webwolf.local
    image: webgoat/reverseproxy
    networks:
      webwolflocal:
        aliases:
          - www.webwolf.local
    ports:
      - 80:80
